"use client";

import { ShoppingBag } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
type CartItem={slug:string;size:string;color:string;quantity:number};

export function AddToCart({slug,sizes,colors}:{slug:string;sizes:string[];colors:string[]}) {
  const [size,setSize]=useState(sizes[0]); const [color,setColor]=useState(colors[0]); const [added,setAdded]=useState(false);
  const add=useCallback((selection={size,color})=>{const current=JSON.parse(localStorage.getItem("l7-commerce-cart")||"[]") as CartItem[];const i=current.findIndex(x=>x.slug===slug&&x.size===selection.size&&x.color===selection.color);if(i>=0)current[i].quantity+=1;else current.push({slug,size:selection.size,color:selection.color,quantity:1});localStorage.setItem("l7-commerce-cart",JSON.stringify(current));window.dispatchEvent(new Event("cart-updated"));setAdded(true);window.setTimeout(()=>setAdded(false),2200);return {product:slug,size:selection.size,color:selection.color,quantity:1,status:"added"}},[slug,size,color]);
  useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"add_product_to_cart",title:"Adicionar produto ao carrinho",description:"Adiciona este produto ao carrinho usando um tamanho e uma cor disponíveis.",inputSchema:{type:"object",properties:{size:{type:"string",enum:sizes},color:{type:"string",enum:colors}},required:["size","color"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const value=input as {size?:string;color?:string};if(!value||!sizes.includes(value.size||"")||!colors.includes(value.color||""))throw new Error("Tamanho ou cor inválidos");return add({size:value.size!,color:value.color!})}},{signal:lifecycle.signal})).catch(()=>undefined);return()=>lifecycle.abort()},[add,sizes,colors]);
  return <div className="buy-box"><fieldset><legend>Tamanho</legend><div className="choice-row">{sizes.map(x=><button type="button" key={x} className={size===x?"choice active":"choice"} onClick={()=>setSize(x)}>{x}</button>)}</div></fieldset><fieldset><legend>Cor</legend><div className="choice-row">{colors.map(x=><button type="button" key={x} className={color===x?"choice active":"choice"} onClick={()=>setColor(x)}>{x}</button>)}</div></fieldset><button className="primary-button full" onClick={()=>add()}><ShoppingBag size={19}/>{added?"Adicionado ao carrinho":"Adicionar ao carrinho"}</button></div>;
}
