"use client";

import Link from "next/link";
import { Boxes, LayoutDashboard, LogOut, Menu, PackageOpen, Plus, Search, Settings, ShoppingBag, TrendingUp, Users, X } from "lucide-react";
import { useState } from "react";
import { storeConfig } from "../config/store";
import { formatBRL, products } from "../data/products";
const orders=[{id:"#1048",customer:"Camila Santos",value:208.8,status:"Pago",time:"Há 12 min"},{id:"#1047",customer:"Jéssica Lima",value:359.8,status:"Separando",time:"Há 43 min"},{id:"#1046",customer:"Mariana Alves",value:139.9,status:"Enviado",time:"Ontem"}];

export function AdminDashboard(){
  const [sidebar,setSidebar]=useState(false);const [tab,setTab]=useState<"visao"|"produtos"|"pedidos">("visao");
  const choose=(value:"visao"|"produtos"|"pedidos")=>{setTab(value);setSidebar(false)};
  const nav=<><button className={tab==="visao"?"active":""} onClick={()=>choose("visao")}><LayoutDashboard/>Visão geral</button><button className={tab==="pedidos"?"active":""} onClick={()=>choose("pedidos")}><ShoppingBag/>Pedidos<span>3</span></button><button className={tab==="produtos"?"active":""} onClick={()=>choose("produtos")}><Boxes/>Produtos</button><button><Users/>Clientes</button><button><Settings/>Configurações</button></>;
  return <div className="admin-shell"><aside className={sidebar?"admin-sidebar open":"admin-sidebar"}><div className="admin-logo"><span>{storeConfig.logoLetter}</span><strong>{storeConfig.name.toUpperCase()}</strong><button className="mobile-only" onClick={()=>setSidebar(false)}><X/></button></div><nav>{nav}</nav><div className="admin-store"><small>Loja ativa</small><strong>{storeConfig.domain}</strong><Link href="/">Ver loja</Link></div><div className="l7-signature"><span>L7</span><small>Commerce</small></div><button className="admin-logout"><LogOut/>Sair</button></aside><main className="admin-main"><header className="admin-top"><button className="mobile-only" onClick={()=>setSidebar(true)}><Menu/></button><div className="admin-search"><Search/><input placeholder="Buscar pedidos, produtos..."/></div><div className="admin-user"><span>LM</span><div><strong>Leandro</strong><small>Administrador</small></div></div></header><div className="admin-content">{tab==="visao"&&<Overview setTab={setTab}/>} {tab==="produtos"&&<ProductsPanel/>} {tab==="pedidos"&&<OrdersPanel/>}</div></main></div>;
}
function Overview({setTab}:{setTab:(tab:"visao"|"produtos"|"pedidos")=>void}){return <><div className="admin-heading"><div><p>Segunda-feira, 21 de setembro</p><h1>Bom dia, Leandro</h1></div><button className="admin-primary" onClick={()=>setTab("produtos")}><Plus/>Novo produto</button></div><section className="metric-grid"><Metric label="Vendas hoje" value="R$ 568,60" note="+18% vs. ontem" icon={<TrendingUp/>}/><Metric label="Pedidos" value="8" note="3 aguardando envio" icon={<ShoppingBag/>}/><Metric label="Ticket médio" value="R$ 142,15" note="+R$ 12,40 esta semana" icon={<Users/>}/><Metric label="Estoque baixo" value="2" note="Produtos para repor" icon={<PackageOpen/>}/></section><section className="admin-card revenue-card"><div className="card-title"><div><small>Faturamento</small><h2>R$ 4.892,40</h2></div><span>Últimos 7 dias</span></div><div className="chart-bars">{[43,61,39,76,58,92,68].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><small>{["S","T","Q","Q","S","S","D"][i]}</small></div>)}</div></section><OrdersTable/></>}
function Metric({label,value,note,icon}:{label:string;value:string;note:string;icon:React.ReactNode}){return <article className="metric-card"><div className="metric-icon">{icon}</div><p>{label}</p><h2>{value}</h2><small>{note}</small></article>}
function OrdersTable(){return <section className="admin-card table-card"><div className="card-title"><h2>Pedidos recentes</h2><button>Ver todos</button></div><div className="table-scroll"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Valor</th><th>Status</th><th>Data</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>{o.id}</strong></td><td>{o.customer}</td><td>{formatBRL(o.value)}</td><td><span className={`status ${o.status.toLowerCase()}`}>{o.status}</span></td><td>{o.time}</td></tr>)}</tbody></table></div></section>}
function ProductsPanel(){return <><div className="admin-heading"><div><p>Catálogo e estoque</p><h1>Produtos</h1></div><button className="admin-primary"><Plus/>Novo produto</button></div><section className="admin-card table-card"><div className="card-title"><h2>{products.length} produtos cadastrados</h2><button>Filtrar</button></div><div className="table-scroll"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Status</th></tr></thead><tbody>{products.map(p=><tr key={p.slug}><td><strong>{p.name}</strong></td><td>{p.category}</td><td>{formatBRL(p.price)}</td><td>{p.stock} un.</td><td><span className="status pago">Ativo</span></td></tr>)}</tbody></table></div></section></>}
function OrdersPanel(){return <><div className="admin-heading"><div><p>Acompanhe as vendas da loja</p><h1>Pedidos</h1></div></div><OrdersTable/></>}
