export const storeConfig = {
  platform: "L7 Commerce",
  name: "Borbogata",
  domain: "borbogata.com.br",
  support: "(71) 99999-9999",
  instagram: "@borbogata_modas",
  instagramUrl: "https://www.instagram.com/borbogata_modas/",
  address: "Rua Simões Filhos, 13 — Boca do Rio, Salvador — BA",
  colors: {
    primary: "#5a2b5b",
    pink: "#ee5799",
    lilac: "#a175b2",
    cyan: "#7acdd4",
    lime: "#cbdd71",
  },
  shippingOrigin: "Salvador, BA",
  installments: 3,
  organizationSlug: process.env.NEXT_PUBLIC_STORE_SLUG || "borbogata",
  demoMode: !process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
} as const;
