import Image from "next/image";
import Link from "next/link";
import { ArrowRight, RotateCcw, ShieldCheck, Truck } from "lucide-react";
import { ProductCard } from "./components/product-card";
import { StoreHeader } from "./components/store-header";
import { storeConfig } from "./config/store";
import { products } from "./data/products";

export default function Home(){return <><StoreHeader/><main><section className="hero"><div className="hero-image"><Image src="/products/macacao-noir.png" alt="Nova coleção Borbogata" fill priority sizes="100vw"/></div><div className="hero-overlay"/><div className="hero-content"><p>Nova coleção · primavera 2026</p><h1>Presença em<br/><em>cada detalhe.</em></h1><span>Peças escolhidas para mulheres que vestem a própria essência.</span><Link href="/produtos" className="light-button">Conheça a coleção <ArrowRight size={18}/></Link></div></section><section className="benefits"><div><Truck/><span><strong>Enviamos para todo Brasil</strong><small>Frete calculado pelo CEP</small></span></div><div><ShieldCheck/><span><strong>Compra segura</strong><small>Seus dados sempre protegidos</small></span></div><div><RotateCcw/><span><strong>Troca descomplicada</strong><small>Até 7 dias após o recebimento</small></span></div></section><section className="collection-section"><div className="section-heading"><div><p>Escolhas da semana</p><h2>Peças que você vai amar</h2></div><Link href="/produtos">Ver coleção completa <ArrowRight size={17}/></Link></div><div className="product-grid">{products.map(product=><ProductCard key={product.slug} product={product}/>)}</div></section><section className="editorial"><div className="editorial-image"><Image src="/products/bolsa-aurora.png" alt="Acessórios Borbogata" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className="editorial-copy"><p>Acessórios</p><h2>O toque final<br/>da sua produção.</h2><span>Detalhes marcantes, acabamentos delicados e combinações que transformam o visual.</span><Link href="/produtos" className="outline-button">Explorar acessórios</Link></div></section></main><footer className="store-footer"><div className="brand footer-brand"><span className="brand-mark">{storeConfig.logoLetter}</span><span>{storeConfig.name.toUpperCase()}</span></div><p>Moda feminina escolhida com cuidado para acompanhar todos os seus momentos.</p><div><Link href="/produtos">Coleções</Link><Link href="/carrinho">Meu carrinho</Link><Link href="/admin">Painel da loja</Link></div><small>© 2026 {storeConfig.name}. Tecnologia {storeConfig.platform}.</small></footer></>}
